# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Honeyboom
description: "Honeyboom offers tools and inspiration to help you build vibrant relationships. Silvia and Michal share their journey as they deepen their relationship with each other, their friends and family, themselves, and people they meet as they travel the world."
email: hello@honeyboom.xyz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://honeyboom.xyz" # the base hostname & protocol for your site, e.g. http://example.com
enforce_ssl: honeyboom.xyz
author: "Honeyboom"
youtube_username: channel/UCFkEEtX7yPtYD0Om0GPwL7w
facebook_username: honeyboom.xyz
medium_username: honeyboom-xyz
disqus_shortname: honeyboom
bg-image: /assets/images/slide-homepage.jpg
enforce_ssl: honeyboom.xyz
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-sitemap


# Site menu settings
menu:
  - title: "Coaching"
    url: "/coaching"
  - title: "Free Tools"
    url: "/free-tools"
  - title: "Silvia & Michal"
    url: "/silvia-michal"

# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path


# Articles url
permalink: /articles/:title/

# SEO
logo: /assets/images/logo/small-logo.png
facebook:
  app_id: 142037946510430
google_site_verification: KWwFj6qqYVxSjMLj6T2C90DDhe1R43dcY5HOtbPOMm4
social:
  name: Honeyboom
  links:
    - https://www.facebook.com/honeyboom.xyz/
    - https://www.youtube.com/channel/UCFkEEtX7yPtYD0Om0GPwL7w
    - https://medium.com/honeyboom-xyz



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
