# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Honeyboom
description: "Dont forget to edit this description"
email: honeyboom.xyz@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.honeyboom.xyz" # the base hostname & protocol for your site, e.g. http://example.com
author: "Honeyboom"
youtube_username: channel/UCFkEEtX7yPtYD0Om0GPwL7w
facebook_username: honeyboom.xyz
medium_username: honeyboom-xyz
bg-image: /assets/images/hb-background.jpg
google_analytics: true
disqus_shortname: webtester5

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-site-map


# Site menu settings
menu:
  - title: "Free Tools"
    url: "/free-tools"
  - title: "Silvia & Michal"
    url: "/silvia-michal"

# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path
# End


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
